trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: PowerShell@2
  displayName: 'Build Code'
  inputs:
    targetType: filePath
    filePath: './build.ps1'
    arguments: >
      -MSBuildFullPath 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe'
      -Verbosity 'diagnostic'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'out\Release'
    ArtifactName: 'POA'
    publishLocation: 'Container'
